### ISSUE TITLE
Is it possible to have subfolders in mp3 folder? 

### ISSUE THREAD

**Issue by ognjiscar** [ben-xo/dir2cast#11]
Hi.
Some of my podcasts are daily and ongoing for a few years now, which makes a lot of files. Right now I have them sorted by the year in subfolders. Is there a way that the script would still work?

Thank you very much.

**Comment by ben-xo** [comment]
It could be adapted; it has to scan all the folders to find out if there is
anything new each time the cache file expires, but checking folders
recursively isn't hard. It should cope fine with thousands of files in a
single folder, though. If you do make changes to support sub folders, feel
free to submit a patch.

**Comment by ben-xo** [comment]
Ok - have implemented this in the branch at https://github.com/ben-xo/dir2cast/tree/feature/subdir-support . Can you try it out and see if it does what you want? 

You need to set the new option in dir2cast.ini RECURSIVE_DIRECTORY_ITERATOR = true

**Comment by ognjiscar** [comment]
It's exactly what I needed and it's working very well.

Thank you so much.

**Comment by ben-xo** [comment]
You're welcome :)

**Comment by ben-xo** [comment]
Merged to master.
