### ISSUE TITLE
No itunes:explicit tag

### ISSUE THREAD

**Issue by Gerlie15** [ben-xo/dir2cast#14]
Hi.
Itunes does not validate rss feeds without itunes:explicit tag.
I added it to dir2cast.php and attached it below. I set default value to 'no'. You can add EXPLICIT  to .ini file.

[dir2cast.zip](https://github.com/ben-xo/dir2cast/files/1821573/dir2cast.zip)

**Comment by ben-xo** [comment]
Can you submit this as a pull request please? Many thanks!

**Comment by ben-xo** [comment]
I've addressed this in https://github.com/ben-xo/dir2cast/tree/feature/explicit-tag - can you test, @Gerlie15 ?
