### ISSUE TITLE
Suggestion: correct headers 

### ISSUE THREAD

**Issue by RobertBozic** [ben-xo/dir2cast#15]
Due to the correct UTF-8 headers of generated podcast file
I suggest a change
at line around 681 to 687
(sorry for mistake in my previous post
https://github.com/ben-xo/dir2cast/issues/12)
```
	public function http_headers()
	{
		header('Content-type: application/rss+xml; charset=UTF-8');
		header('Last-modified: ' . $this->getLastBuildDate());
	}
```
to
```
	public function http_headers()
	{
		header('Content-type: text/xml; charset=UTF-8');
		header('Last-modified: ' . $this->getLastBuildDate());
	}
```
all the best

**Comment by ben-xo** [comment]
The correct content type is application/rss+xml according to https://stackoverflow.com/questions/595616/what-is-the-correct-mime-type-to-use-for-an-rss-feed

**Comment by ben-xo** [comment]
…however I note that the same page says that "text/xml" has been the de-facto standard for some time, so I will fix this.
