### ISSUE TITLE
Not Items found in... (question)

### ISSUE THREAD

**Issue by DC7IA** [ben-xo/dir2cast#17]
Hi,,

thanks for developing dir2cast. Very useful for me.

Now I've got a question. I've installed dir2cast to another server. 
Same configuration, but I get "No Items found in /path/path". 

The path exists, the files exist, they're publicly accessible and it works with the exact same configuration. What could cause this?

dc7ia

**Comment by DougBarry** [comment]
@DC7IA assuming you're using linux, is SELinux enabled?

**Comment by ben-xo** [comment]
Paths starting with / are absolute paths - and the path of your public web folder on the server may not be different.

If you put a file containing <?php phpinfo(); ?> into phpinfo.php and view it, it may tell you what the PATH your new server has compared to your old server.
