### ISSUE TITLE
Bug: Some characters break the feed

### ISSUE THREAD

**Issue by DC7IA** [ben-xo/dir2cast#20]
I put `Radio24syv sender uafhængige nyheder hver time, døgnet rundt - når klokken bliver hel.` into description.txt and this broke the feed. Removing æ, ø and å from the description made it working again.

If I leave it in, I don't see a description, image or files. It's just the headline that's left.

This seems to be a bug. Using CentOS 7 server.

**Comment by DC7IA** [comment]
It works if I replace those characters with any other character A to Z.

**Comment by ben-xo** [comment]
Would it be possible to get a copy of the specific description.txt you are trying? I'd like to see if there's an encoding issue and debug accordingly.

**Comment by ben-xo** [comment]
Just wanted to follow up on this. Are you still having the issue? Can I get a copy of the description.txt you used?

**Comment by ben-xo** [comment]
I believe this is now fixed. Please re-open if you have any further issues!
