### ISSUE TITLE
ID3 tags fail on large files

### ISSUE THREAD

**Issue by mattCameron09** [ben-xo/dir2cast#24]
For mp3 files over ~250 MB, I am unable to read the ID3 tags. The feed still loads, but for those items, the description is blank and the title is set to "(untitled)."

**Comment by DickManhard** [comment]
I would like to mention that you should add the php-xml requirement in the readme.txt. Great program thus far.

**Comment by ben-xo** [comment]
@DickManhard I've added a note about the XML requirement to the README.

@mattCameron09 I've not experienced this myself. ID3v2 tags are at the beginning of the file (id3v1 tags are at the end), so it shouldn't really matter how big the file is!

**Comment by ben-xo** [comment]
@mattCameron09 if this is still an issue for you, can you provide me with an example file?

It may be possible to work around the issue by simply resaving the file with a new tag.

In any case, it would help me to understand what the problem is.

**Comment by ben-xo** [comment]
@mattCameron09 just a nudge - can you let me know if you still have an issue here?

**Comment by mattCameron09** [comment]
@ben-xo Thanks for the nudge. I moved to another system for the large files a few years ago. I just spun this back up using the files that I think I had hosted before. Whatever the problem was, it seems to be resolved now. I'll create a new issue if it crops up again.
