### ISSUE TITLE
Automatically extract cover art from media files for episodes

### ISSUE THREAD

**Issue by ben-xo** [ben-xo/dir2cast#28]
Suggested on another issue. Use embedded cover art.

**Comment by ben-xo** [comment]
@nitaaikumar  would you like to try the  feature/automatic-cover-art  branch? It should extract episode covers automatically and put them into the folder with the media files.

**Comment by nitaaikumar** [comment]
Yes I would. Please add me @ben-xo. I am new to github, how will I be able to download and try it?

**Comment by ben-xo** [comment]
On the `Code` tab click `Branch` and choose that branch. Then, click `Clone or Download`, and then `Download Zip`.

**Comment by ben-xo** [comment]
This is now in release 1.18

**Comment by nitaaikumar** [comment]
Thanks so much. Sorry could not reply faster as swamped with tasks here. I downloaded and replaced the files on the server but still can't see the cover image tags in the rss feed at: https://gorich.org/dir2cast.php. How does this work? Will the cover image get extracted from the media file and that link be added to the podcast feed or that is not required and it will directly show? I will donate for this too. I have to just get the feed to work in Power Casts by changing the path I guess.

**Comment by ben-xo** [comment]
@nitaaikumar you should delete all the files in the temp folder - otherwise you'll be seeing a cached version of the podcast. (It normally only gets regenerated when you upload a new file).

**Comment by nitaaikumar** [comment]
thanks @ben-xo. What do I expect to see? I deleted the file in the temp folder. Still not seeing any  images tags in the above feed. And also @ben-xo this problem of Check you internet connection in Pocket Casts for this specific feed is still there. The media urls are correct in the feed php. And I can access the media publicly and directly. So maybe there is something in the feed, which is making Pocket Casts give this error? Please if you can install Pocket Casts in your phone and check with your server feed. In the Discover tab, you just have to type the full url to the podcast feed and subscribe. I will be grateful if you can please fix this too. Thanks.

**Comment by ben-xo** [comment]
Sorry to keep making you download more files. Can you try with the very latest dir2cast from the releases tab (v1.18)

This version happily extracts images from my mp3s. If it's not working from an mp4, send me a link to an mp4 with an image embedded and I'll see what I can do.

Can we keep the Pocket Casts discussion to the other ticket? Easier for me to have the discussions separately. What URL are you putting into Pocket Casts? I downloaded it so I can try it out. (My personal podcast loads fine)

**Comment by nitaaikumar** [comment]
Ok @ben-xo. I will post in the other issue. I tried with a mp3 and it extracted the cover image perfectly and showed the image tag. But it is not extracting the cover images from a m4a and mp4. Both the files have below have cover images, including the mp4. You can please try with them about why it is not extracting.

https://gorich.org/NitaaiMeditation.mp4
https://gorich.org/Love-is-in-the-Air.m4a

**Comment by ben-xo** [comment]
Reopening as it apparently only works for MP3s so far. I will investigate.

@nitaaikumar just to be sure I'm getting the result you want:
* how did you add the cover image?
* can you show me what the cover image should look like, for each of the files?

This will greatly help me working out what's not working properly.

**Comment by nitaaikumar** [comment]
I added them via the [Metadatics](https://apps.apple.com/us/app/metadatics/id554883654?mt=12) Mac app, which is quite a standard and very good.

https://gorich.org/m4acover.jpg
https://gorich.org/mp4cover.jpg

are the respective cover images embedded.

**Comment by ben-xo** [comment]
Sir, it's your lucky day. Have a play with version 1.19, it correctly extracts cover art from your files now ;)

It was a little more complicated than I expected - i'm very pleased with the results

**Comment by ben-xo** [comment]
I believe this now works very well!

**Comment by nitaaikumar** [comment]
Wow wow @ben-xo, it really does. So awesome, we just need to make media file with id3 tags and our podcast is ready. Now dir2cast has become just perfect and future-proof with the complete support for the most popular audio and video formats. Just wish this Pocket Casts issue was not there (will try from another server, with mp3 etc) and I will be just good to go to create something beautiful for the world, without having to mess with server podcast scripts like powerpress or something which can easily take upto 5-10 mins to add an episode. Have donated for this again. Thanks so much.

**Comment by ben-xo** [comment]
You're welcome and I very much appreciate the donations.
