### ISSUE TITLE
Podcast feed giving error in Pocket Casts

### ISSUE THREAD

**Issue by nitaaikumar** [ben-xo/dir2cast#29]
The Pocket Casts app is the best free app for both iOS and Android. It even shows all the 1000s of episodes in the feed unlike Apple Podcasts which shows only 300. When I add my https://gorich.org/dir2cast.php feed to Pocket Casts it first some error that feed is not proper and then now it is constantly showing the error: Check your internet connection and try again, even though it is downloading episodes from other podcasts fine with the internet connection. Please @ben-xo fix the podcast feed with Pocket Casts otherwise I can't share my dir2cast feed with anyone as mostly everyone listens on their phones nowadays. Thanks. I have just donated $50.

**Comment by ben-xo** [comment]
Hi there,

https://gorich.org/dir2cast.php looks like it only has 3 episodes?

You'll need to give me more information about what it says along with "not proper" - i need the details.

"Check your internet connection and try again" means the page didn't load for you, which could mean the feed timed out as it's too slow or too big - I cant easily fix that, but also it could just be a temporary problem at your end.

I'll take a look at Pocket Casts, but I'd like to see the real feed that you plugged into Pocket Casts first.

**Comment by nitaaikumar** [comment]
I stand corrected @ben-xo. The podcast works in the Apple Podcasts app and the Castbox app also. It is giving this error only in Pocket Casts. Actually Pocket Casts is my podcast app of choice and I recommed it to all my listeners as it totally free even of ads cross platform, it plays my portrait video mp4 episodes (Castbox supports only landscape videos), it shows 1000s of episodes in feeds (Apple shows only 300), Pocket Casts has a great short universal url for our podcasts which we can give, and finally the home screen of the app is our own Library of subscribed feeds so it does not push its own directory on us like the free version of Castbox does when it loads every time. If your mp3 podcast is working in Pocket Casts, I have to check it mp3. As I checked it only with m4a and mp4. Thanks.

**Comment by ben-xo** [comment]
It might be worth reporting the issue directly to Pocket Casts, as they know their app best! It can't hurt, anyway!

**Comment by nitaaikumar** [comment]
Yes @ben-xo, I will. First I will check if mp3 only feed works. Then I will make a final mixed feed and report it to them. I don't want to make multiple shows each 300 episodes just because Apple only shows 300. Spotify also shows all the 1000s of episodes in one feed. So so Pocket Casts, Castbox, Anchor, etc. I will also check it on Podcast Republic on android.

**Comment by ben-xo** [comment]
@nitaaikumar i noticed your podcast feed has many blank fields (e.g. description) - perhaps uploading some of the .txt files or editing dir2cast.ini would solve the problem

**Comment by nitaaikumar** [comment]
Yes @ben-xo. I checked it https://podba.se. There is only one error coming, everything else is perfect:

Podcasts should have a valid <itunes:summary> tag, or at least a <description>.

Could you please add an auto summary tag with same the id3 title for now and maybe later extract the id3 lyrics and show them in this itunes summary tag automatically? That would be so awesome and dir2cast feed will be 100% in podba.se. Metadatics has the Lyrics tab and Comments tab to add a description.

**Comment by ben-xo** [comment]
@nitaaikumar I've set the default description (and therefore also itunes summary) to "Podcast" in the most recent commit. You can change this by editing dir2cast.ini and uploading your preferred settings.

**Comment by nitaaikumar** [comment]
@ben-xo On second thoughts, it would be great if the id3 title is added as the summary and lyrics are added as the description as lyrics can also be transcripts of that audio or video, so it may be longer, so description field may be more appropriate for the lyrics.

**Comment by ben-xo** [comment]
If you add a description in the comment field, for an individual episode, it should already pick that up for an individual episode summary!

**Comment by nitaaikumar** [comment]
Wow really? the id3 comments field works as the description? hope it works for m4a and mp4 too again and not just for mp3 as before. I will add a comment to both and upload.

**Comment by ben-xo** [comment]
@nitaaikumar yes indeed. That's how I do it for my own podcast https://xo.am/dnb/bd/dir2cast.php

**Comment by nitaaikumar** [comment]
One last error in podba.se. Podcasts must have a valid <itunes:category> tag to be accepted for iTunes.

**Comment by ben-xo** [comment]
Again, you can set that in dir2cast.ini .

**Comment by ben-xo** [comment]
@nitaaikumar open dir2cast.ini in TextEdit (or whatever) and have a read - it's self-documenting

**Comment by nitaaikumar** [comment]
Wow wow wow, now pocket casts works finally. Thanks a million. Oh my my even the description is showing perfectly from the comments id3 in pocket casts, castbox, and apple podcasts is showing up perfectly as each episode note. You made my day, feel very happy today. Now no one in the world can make an excuse not to podcast, as it has become as simple and just drag and drop on the server.

**Comment by ben-xo** [comment]
@nitaaikumar your words warm me greatlty. It was always my intention (since I wrote the bulk of this program, 11 years ago) for it to be as simple as step 1: upload the files. step 2: done. I'm very glad you're making use of it.

**Comment by nitaaikumar** [comment]
@ben-xo One question, the default has been set to 10 items. But it will support 100s or 1000s of audio or video files right? Or it will overload the server? I mean how much do you think is maximum? Will it parse even 1-1.5mb feeds with 1000s of episodes?

**Comment by nitaaikumar** [comment]
> It was always my intention (since I wrote the bulk of this program, 11 years ago)

Aww thanks so much @ben-xo. Actually it is the masterstroke and simplicity of your script. I am so so late, 11 years late to use it. Maybe podcast hosting companies don't want anyone to know of your script or they will be out of business, hehe, kidding. I think people go to them for feed stats.

Oh that gave me another idea. maybe if you can some flat file counter or something which counts the number of plays and downloads, hehe. At least basic stats. Number of plays/downloads enthuse the podcast producer.

**Comment by ben-xo** [comment]
@nitaaikumar the way it works is that 99% of the time it serves the feed from the cached file, which is pretty much instant. However, the first time you view the feed after uploading a new episode, it has to rebuild the entire feed.

To do that, it looks at however many files you've configured. If there are too many, it may not work - it may be too slow. You will have to try it and see.

In an ideal world, I would make the program incremental, so that it only has to add the new episode, not rescan every episode. However, that's a substantial change to the program and I have not had a need for it myself.

Please let me know how you go. 1000 episodes for a single podcast is a very large number…

In unusual or extreme situations like this, all is not lost. It is possible to run dir2cast.php not via the web server, to 'pre-cache' the cache file. However I can't really offer support on how to do this, as there are so many variables and every situation is different.

**Comment by ben-xo** [comment]
Counting plays and downloads is more of a web-server thing, and it's difficult to track accurately - but, you can always use FeedBurner! https://feedburner.google.com/

**Comment by nitaaikumar** [comment]
> Please let me know how you go. 1000 episodes for a single podcast is a very large number…

Thanks for the elaborate answer. I have seen anchor.fm podcasts with 1600 episodes both on anchor and spotify, so I guess spotify does not restrict it. 

thanks for the feedburner suggestion. Feedburner has a few issues. the 1 billion online chinese people won't be able to access the podcast feed url at all as google is blocked there. podcasts are picking up there. Plus feedburner probably would truncate the feed and not let all the episodes pass through, like 1mb it allows I think.

**Comment by nitaaikumar** [comment]
@ben-xo has your dir2cast feed been approved by apple in its podcast directory? or anyone who else's? just curious to know. I guess apple won't have any issues since it is validates fully.

**Comment by ben-xo** [comment]
@nitaaikumar those excellent points. I don't know if feedburner is blocked in china, as it's not the same as google search.

Regarding large podcasts: I believe the RSS standard (on which podcasts are based) has a syntax to allow pagination - that is, page 1, page 2, etc. So it would (theoretically) be possible to divide up your back catalogue into smaller sub-podcasts which are linked together - and it would (or... should) be completely transparent to the listener. (https://stackoverflow.com/questions/1301392/pagination-in-feeds-like-atom-and-rss) However, again, it's not something I've needed myself, so I've not looked into it. It could get a little complicated.

Regarding iTunes: yes, my feed is in the itunes directory. However I have to say - it's been there for many years, so it may not have had to pass as thorough a check - i don't know really. Feedback appreciated

**Comment by nitaaikumar** [comment]
> In an ideal world, I would make the program incremental, so that it only has to add the new episode, not rescan every episode.

Wow, you are so brilliant and full of options @ben-xo. Thanks. So to support 1000s of episodes, you have given 3 options:

1. incremental update
2. pre-caching the cache file
3. pagination.

Just summarizing. I like the pre-caching option I think. if the whole feed is cached then it could be like a static php file which could easily support 1000+ episodes.

**Comment by ben-xo** [comment]
with pre-caching, you still have to figure out how to get it to run the first time. and without incremental update, it will gradually get slower and slower to generate after a new upload, the more files there are. (Of course once it's generated, it's very fast).

incremental update would actually be the best option. essentially, caching data per file rather than just caching the end result. I will have a think about it.

**Comment by ben-xo** [comment]
I just tested creating a podcast of ~500 shows on my computer, it took 32 seconds to generate. Some web servers have a 30s limit. Anyway - let's solve this problem when it actually happens!

**Comment by nitaaikumar** [comment]
> I will have a think about it.

Wow, thank you so much. Actually it is so easy to drag and drop media on the server that I think it will be even easy to make podcasts of a huge collection of old mp3s for example. In such a case scenario, no one would use a podcast host or podcast script where one has to manually add each episode. so your script actually shines when there are 100s or 1000s of episodes or old music collections and one can hear offline as there is a nice "download all" button in pocket casts..so if it can support that, then listeners are in for a huge treat.

i just checked feedburner is blocked in china as it is a subdomain of google.com.

yes incremental update will be the best. but even if everytime a new listener subscribes, the server is not strained and it just has to access a static feed file that would solve the problem i think. maybe some cron once a day to run the php and generate a static file. forgive me i am a noob in coding.

**Comment by ben-xo** [comment]
@nitaaikumar we can start to worry about it after we get to ~400+ episodes. Bear in mind that a large feed will also take longer to download, so ultimately I would still recommend a cap - and perhaps a second feed as an archive of older material.

**Comment by nitaaikumar** [comment]
let me explain why this idea of 1000s of episodes is important. the chinese can't access youtube or soundcloud without a vpn. youtube degrades the audio quality to 128kbps of the original high quality audio. we can make a zip file of all the audio/video available and then can unzip it and play it. in a big podcast, the advantage is that the listeners can select the episodes which they want to download and keep offline. in a zip file, they will have to download it all. and search is instant. plus podcast apps remember one has listened of each episode and starts from there. this can't be achieved by playing for an unzipped folder. they can quickly share the podcast feed link to others unlike a download of a huge zip file. and so on. Sorry i am just blabbering here.

**Comment by ben-xo** [comment]
I appreciate your big thinking! as an engineer, one of the principles I adhere to is... build it when you need it, but not before then ;) (and when the time comes, we'll get this fixed!)

**Comment by nitaaikumar** [comment]
> so ultimately I would still recommend a cap - and perhaps a second feed as an archive of older material.

Anchor.fm makes such big feeds. here is one podcast with 1471 episodes:  https://anchor.fm/optimal-living-daily. Thank you.

**Comment by nitaaikumar** [comment]
whenever you have time. my offer stands. i can donate for your time for this addition. to make such changes that your script will easily take upto 5000 episodes without any signficant load on the server (full caching maybe). I am saying this because I already have 1500 very old videos/audios of mine which I would like to turn into a podcast.

**Comment by ben-xo** [comment]
@nitaaikumar lets raise a new issue for the feature and i may be able to work on it later in the holiday season.

**Comment by nitaaikumar** [comment]
Done @ben-xo thanks, you can close this issue as it is resolved now.
