### ISSUE TITLE
Tuning the script for huge collections of media on the server

### ISSUE THREAD

**Issue by nitaaikumar** [ben-xo/dir2cast#30]
As suggested by you @ben-xo, opening a new issue. Maybe the script generating a full static cached file once a day automatically instead of the server doing all the heavy lifting on the fly for every access to the file. I know we can just copy the generated code manually into a static feed file everytime we upload new files but will be great if the script is automated to do that or something.

**Comment by ben-xo** [comment]
I've tentatively addressed this in https://github.com/ben-xo/dir2cast/tree/feature/cache-id3-data-per-file . Will merge after more testing.

**Comment by nitaaikumar** [comment]
Wow thank you so much dear @ben-xo. This is so wonderful. Will test it and let you know. Any coding remaining or it is completed and just needs to be tested?

**Comment by ben-xo** [comment]
It just needs to be tested!

If your folder of media is very large from the word go, it will still take a long time to generate.

But, if you add a few files regularly and it grows large over time, it should be very quick to add each new episode. (Previously, it would rescan everything every time you added a new episode). So the thing to test is that it can grow large a few files at a time.

You can also achieve the same result by gradually increasing the number in dir2cast.ini which represents the number of episodes to display, from ITEM_COUNT=10 upward (e.g. 10 at a time).
