### ISSUE TITLE
Still shows 10 items after increasing item count

### ISSUE THREAD

**Issue by nitaaikumar** [ben-xo/dir2cast#32]
@ben-xo I uncommented ITEM_COUNT in the ini file and made it 9999. But the php file still shows 10 items only. I tried reducing the default Expiry time etc. but still 10 items. Am I forgetting to change something or is this a bug? I tried both the stable version and with the id3 cache testing version.

**Comment by nitaaikumar** [comment]
I changed it to 9999 in the php file too but still it shows only 10 items. Using PHP 7.4.

**Comment by nitaaikumar** [comment]
In version 1.19, if I change the ITEM_COUNT to 99 instead of 10, it gives the following error:

Trying to access array offset on value of type bool
This error occurred on line 218 of /path/dir2cast.php. 
Warning: unlink(/pathtotemp/somename_public.xml): No such file or directory in dir2cast.php on line 1131.

When I change it back to 10 it is fine. So there seems to be some bug with increasing the ITEM_COUNT @ben-xo

**Comment by nitaaikumar** [comment]
Oh I downloaded the latest one from: https://github.com/ben-xo/dir2cast/tree/d35fde0ddf81e29062e1acdbfc252e33ab06aa98 and it works, seems to show all items now. Will let you know if I encounter any more issues.

**Comment by nitaaikumar** [comment]
Facing another issue now. It is not taking any value of TITLE, LINK, etc. from the ini file after uncommenting and setting them to the desired values. It still shows the public directory's name as the name of the Podcast.

**Comment by ben-xo** [comment]
Every time you change something in dir2cast.ini you must delete the content
of the temp folder too.
-- 
--
Ben

**Comment by ben-xo** [comment]
I can definitely make it check if the config file has been updated - i may do that - it will make it easier to test changes.

**Comment by nitaaikumar** [comment]
Thank you so much @ben-xo if that is possible. 

Sorry this is off-topic, but is it possible to disable the script from extracting the cover images from the media files and not add the cover image code in two places at <itunes:image href="url"/> and <image>url</image> for each episode to make the feed smaller for a large collection of audio and video files? And use the same cover image for each episode as the 1400x1400 image for the show? A global episode image I mean. Because when we have a huge collection of audio and video files, we don't want to manually add cover images for each episode and want it to just use the same cover image of the show for each episode. And also we want the feed to be as small as possible.

<itunes:summary> and <description>,  <link> and <enclosure url="">, and <itunes:author> and <itunes:subtitle>, and <itunes:image> and <image> have the same values. So can you please provide a settings in the ini to disable one of each of these 4 to make the feed more smaller for large items? We may not want to add the feed which has a lot of episodes on Apple Podcast and just tell them to add to a Podcast app directly which accepts podcast feed urls.

I will donate for this caching feature as soon as possible. Sorry for the delay.

**Comment by ben-xo** [comment]
v1.21 makes it much easier to experiment with changes to dir2cast.ini as you don't have to keep deleting the cache file.

Regarding the image and other tags in the file: the duplication in the text of the feed may seem excessive but your web server will (or… should) send a gzipped copy of the text to the podcast app, meaning what the app downloads is generally much smaller than the feed size itself.

You can check if your server is sending a compressed feed with this tool: https://varvy.com/tools/gzip/ (paste the dir2cast.php URL in). My feed is serving with a 75% reduced size because of gzip. Because of the way gzip works, removing duplicate tags hardly affects the actual transmitted size at all.

**Comment by ben-xo** [comment]
When I test the other URL you gave me, https://gorich.org/dir2cast.php at the link above, it is already gzip enabled, and is 85% smaller.

**Comment by ben-xo** [comment]
@nitaaikumar if you want to use a global cover art, without extracting from each media file, set:

```
ITUNES_IMAGE = http://www.somewhere.com/podcast.jpg
AUTO_SAVE_COVER_ART = false
```

both of these settings are already in dir2cast.ini :)

**Comment by nitaaikumar** [comment]
Dear @ben-xo, Never knew about this gzipping. Yes, I am getting 81% reduction. It is just great. Will try 1.21. I hope it still keeps all the caching benefits for lot of items which you added recently.

Yes, found the AUTO_SAVE_COVER_ART = false and it works. Did not know if the ITUNES_IMAGE would show for each episode also. Just perfect.

For one of my domain names, I have even set dir2cast.php as index.php. So I just tell them to go their favorite podcast app and type the https://domainname and voila they see the podcast feed and can subscribe to it. What as easy to subscribe to a podcast? All thanks to your persistent efforts, dir2cast is becoming a fully dream-come-to script.
