### ISSUE TITLE
Remove .mp3 / .m4a Extension On RSS Feed Title 

### ISSUE THREAD

**Issue by x3r4n0** [ben-xo/dir2cast#41]
hey i have some .m4a files on my webserver and all is working fine but is it possible to remove the media extensions on the Podcast Showtitles? i have no id3tags on my files. dir2cast use the title of the filesnames. like "DJ - Party.m4a the Show is called  "DJ - Party.m4a"

is it possible?

**Comment by ben-xo** [comment]
Hi there (and sorry that I never replied to this 10 years ago…)

If the m4a files have metadata (e.g. artist = DJ, title = Party) these will be used. The filename is only shown when no metadata is present at all.
