### ISSUE TITLE
Does dir2cast fully work for PHP 8.0 or you will need to fix it?

### ISSUE THREAD

**Issue by nitaaikumar** [ben-xo/dir2cast#43]
Dir2cast has made my life so much easier. Thanks Ben. Hope you can make it work with PHP 8.0 too so that it will parse larger podcast feeds even faster with the help of the 8.0 benefits.

**Comment by ben-xo** [comment]
Hi there, as far as I know it works with PHP 8 just fine :) let me know if that's not the case

**Comment by ben-xo** [comment]
I tested it just now and it appears to work fine with PHP 8.

**Comment by ben-xo** [comment]
@nitaaikumar can you confirm this issue is resolved for you?

**Comment by ben-xo** [comment]
The test suite now proves it works with PHP7.4 and 8.0
