### ISSUE TITLE
file ordering in xml file

### ISSUE THREAD

**Issue by DickManhard** [ben-xo/dir2cast#44]
There doesn't seem to be any ordering in the generated dir2cast XML file. When generating a podcast or audiobook rss, it would be nice to have them in title/track order or something like that. Instead, the XML file lists the mp3s in no particular order.

**Comment by ben-xo** [comment]
Hi @DickManhard , 

The ordering in the file is based on the dates the files were added to the folder. You should upload the files in the order you wish them to appear in the feed, newest last. (This corresponds to the original intended use-case, which is for publishing episodes one at a time).

If you have an entire series ready to go in one go, I appreciate that this might be a little trickier to set up. If you're not comfortable using tools such as `touch` to fake the "update" the dates one by one, then other ways to do it include:
* copying the files to a new folder one by one, in the order you want them to appear
* deleting them and re-uploading them one by one, in the order you want them to appear
* editing the metadata / tags on the files one by one, in the order you want them to appear

If for some reason none of these are possible them I apologise that your use case isn't yet supported. Whilst I'd be interested to know why this isn't possible, I could add a new configuration setting to allow a different method of publishing.

However, please be aware that Dir2cast is quite reliant on file modification dates to determine if it needs to refresh the feed, and to determine if it needs to re-scan the contents of the files. (If you accidentally do any of the above on pre-existing files, it will bump them to to the top of the podcast).

**Comment by DickManhard** [comment]
OK, that makes sense. I'll try to mod the dates and re-scan.
Thank you for your time.

**Comment by ben-xo** [comment]
@DickManhard if this solves your problem (or, if it does not), either way I would appreciate you leaving feedback here so we can close the issue. :) thanks!

**Comment by DickManhard** [comment]
Works fine with the touch program to modify audiobook chapters in reverse order.

**Comment by ben-xo** [comment]
> Works fine with the touch program to modify audiobook chapters in reverse order.

I appreciate you confirming the outcome!

**Comment by stirtingale** [comment]
I realise this is closed but I found it fairly annoying to have to loop through a big library of content and manually update each folder

This is a simple recursive script that will loop through every sub-folder in a directory ( i.e. /audiobooks ) and will updated the modification times using touch 

https://gist.github.com/stirtingale/2d66ec6a0557267a2238e59f455efd59

It will respect numeric ordering ( i.e. if it is 001.mp3, 099.mp3, 100.mp3 ). 

Hopefully helpful to anyone who has found this thread by Googling how to sort by filename!
