### ISSUE TITLE
Error: fopen(/var/www/CriticalRole/temp/bb4784c507a72f843b617cb5601ec6d6__var_www_CriticalRole.xml): failed to open stream: No such file or directory (on line 948 of /var/www/CriticalRole/dir2cast.php)

### ISSUE THREAD

**Issue by alexkibler** [ben-xo/dir2cast#5]
Hi there.  I know there hasn't been any activity here in ages, but I figured it's worth a shot.  I've got a directory of MP3s on an ubuntu 12.04 server with the LAMP stack, PHP 5.3, but I'm getting this error when trying to set up.  I left the ini totally blank, but for whatever reason, this is happening.  Any idea why?

**Comment by ben-xo** [comment]
That file is the cache file. It tries to put it in /tmp but on shared
hosting maybe you can't write to tmp. Try putting an actual path in the ini
file
