### ISSUE TITLE
Support for .m4b files

### ISSUE THREAD

**Issue by crosbyh** [ben-xo/dir2cast#59]
Hello,

 Thank you for this very useful piece of software! I am wondering if it would be possible to add support for the .m4b format?

I own several audiobook files in .m4b format, and using dir2cast to bring them into my phone's podcast client would make for an ideal listening experience!

**Comment by ben-xo** [comment]
Hi there, yes that should be pretty straightforward! Unfortunately I don't have any m4b files to test with, can you point me to some free ones I can use to check it's working?

**Comment by crosbyh** [comment]
Thank you for the response! Here are some Project Gutenberg directory links, which contain public domain m4b audiobook files you can download:

https://www.gutenberg.org/files/21179/m4b/
https://www.gutenberg.org/files/20673/m4b/
https://www.gutenberg.org/files/21520/m4b/

**Comment by ben-xo** [comment]
Great, thank you! And thanks once again for your support! :D
