### ISSUE TITLE
Enclosure Url Problem

### ISSUE THREAD

**Issue by bisherbas** [ben-xo/dir2cast#6]
Urls are populated incorrectly. Example:

`<enclosure url="file:///home3/userID/public_html/`

Can you please help? Since url does not start with http, podcast is unable to play the mp3 files.

**Comment by ben-xo** [comment]
This means your web server isn't passing the "Host" header through correctly to the script. How are you running it?

If you aren't running it using a web server, you'll need to edit dir2cast.ini to define an MP3_URL.
