### ISSUE TITLE
Support season tag

### ISSUE THREAD

**Issue by EdwarDDay** [ben-xo/dir2cast#65]
It would be nice to have support for the season tag. iTunes supports `<itunes:season>` as an optional episode tag and there is the `TPOS` (`part_of_a_set`) ID3 tag which could be used.

**Comment by ben-xo** [comment]
This is an interesting idea, i'll look into this!

**Comment by EdwarDDay** [comment]
When I look at Apples [Podcaster's Guide to RSS](https://help.apple.com/itc/podcasts_connect/#/itcb54353390) there is the definition of `<itunes:season>`
> The episode season number.
>
> If an episode is within a season use this tag.
>
> Where season is a non-zero integer (1, 2, 3, etc.) representing your season number.
>
> To allow the season feature for shows containing a single season, if only one season exists in the RSS feed, Apple Podcasts doesn’t display a season number. When you add a second season to the RSS feed, Apple Podcasts displays the season numbers.

So a non-zero positive integer should work.

**Comment by ben-xo** [comment]
Implemented here: https://github.com/ben-xo/dir2cast/pull/68

**Comment by EdwarDDay** [comment]
Thanks @ben-xo .
I tested it and found out, that just adding a `<itunes:season>` element isn't enough. The whole podcast needs a `<itunes:type>serial</itunes:type>` and every episode needs an episode number `<itunes:episode>`.

My idea for continuing would be the following:
Adding `<itunes:type>serial</itunes:type>` based on `ITUNES_SEASON_TAG` in the ini file would make sense in my opinion. The episode number could either be calculated or read from `TRCK` tag (`Track number/Position in set`).

**Comment by ben-xo** [comment]
Hi @EdwarDDay , I have updated the branch as so:
* config renamed to ITUNES_TYPE_SERIAL
* when set, <itunes:type>serial</itunes:type> will be output.
* TRCK now used for <itunes:episode> as well as TPOS for <itunes:season>. If missing, won't be output.

Could you try this version?

**Comment by ben-xo** [comment]
I've updated the config to e.g. `ITUNES_TYPE = serial` with the default being `episodic` so that you have the option to remove it entirely with `ITUNES_TYPE = ""`

**Comment by EdwarDDay** [comment]
@ben-xo I tried it and it works perfectly. Thank you
